export const GET_WEATHER_BY_CITY1 = "GET_WEATHER_BY_CITY1";
export const GET_WEATHER_BY_CITY2 = "GET_WEATHER_BY_CITY2";
export const GET_WEATHER_BY_LOCATION1 = "GET_WEATHER_BY_LOCATION1";
export const GET_WEATHER_BY_LOCATION2 = "GET_WEATHER_BY_LOCATION2";
export const GET_LOCATION = "GET_LOCATION";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
